dependencies:
- python=3.7.4
- pip=19.2.3
- pip:
    - tensorflow==2.0.0b0
    - jupyter==1.0.0
    - ipykernel==5.1.2
    - matplotlib==3.1.1
    - scikit-learn==0.21.3
    - nltk==3.4.5
    - spacy==2.2.3
    - pyLDAvis==2.1.2
    - gensim==3.8.1
    - en-core-web-sm
    - pytest
    - pytest-mpl
    - pytest-mock
    - PyYAML
    - click==7.0
    - pandas==0.25.1
    - numpy==1.16.5
    - tqdm==4.36.1












